"""Build the Pehredar Python core as a standalone PyInstaller binary.

Produces ``pehredar-core(.exe)`` (scan CLI) in
``gui/resources/bin/<win|linux>/`` so the Electron installer ships zero
external dependencies (no system Python needed).

Usage (from the repo root)::

    pip install pyinstaller          # or: pip install -e ".[dev]"
    python scripts/build_core.py                 # auto-detect platform
    python scripts/build_core.py --platform win
    python scripts/build_core.py --platform linux

Notes:
- PyInstaller ``--onefile`` is used; the entry points are tiny generated
  wrappers with absolute imports (``from pehredar.cli import main``) because
  a frozen ``__main__`` script cannot use package-relative imports.
- ``stalkerware_db.json`` is bundled via ``--add-data`` and also resolved
  through ``sys._MEIPASS`` in ``pehredar/checks/stalkerware_db.py``.
- ``--console`` (default) is kept so ``--version``/errors work when run
  manually; the GUI spawns the binary with ``windowsHide: true``.
"""

from __future__ import annotations

import argparse
import os
import platform
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GUI_BIN_ROOT = REPO_ROOT / "gui" / "resources" / "bin"

ENTRIES = (
    ("pehredar.cli", "main", "pehredar-core"),
)

DB_SRC = REPO_ROOT / "pehredar" / "checks" / "stalkerware_db.json"


def detect_platform_dir() -> str:
    system = platform.system().lower()
    if system == "windows":
        return "win"
    if system == "linux":
        return "linux"
    raise SystemExit(f"Unsupported build platform: {platform.system()} (expected Windows or Linux)")


def check_pyinstaller() -> None:
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        raise SystemExit("PyInstaller is not installed. Run: pip install pyinstaller  (or pip install -e \".[dev]\")")


def write_entry_module(workdir: Path, package: str, func: str, name: str) -> Path:
    workdir.mkdir(parents=True, exist_ok=True)
    entry = workdir / f"entry_{name.replace('-', '_')}.py"
    entry.write_text(
        f'"""PyInstaller entry wrapper (generated by scripts/build_core.py)."""\n'
        f"from {package} import {func}\n\n"
        f"if __name__ == '__main__':\n"
        f"    {func}()\n",
        encoding="utf-8",
    )
    return entry


def build_one(entry: Path, name: str, distdir: Path, workdir: Path, add_data: str) -> Path:
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--onefile",
        "--noconfirm",
        "--clean",
        "--name",
        name,
        "--distpath",
        str(distdir),
        "--workpath",
        str(workdir / "build"),
        "--specpath",
        str(workdir / "spec"),
        "--paths",
        str(REPO_ROOT),
        "--add-data",
        add_data,
        "--hidden-import",
        "click",
        "--hidden-import",
        "rich",
        str(entry),
    ]
    print(f"+ {' '.join(cmd)}")
    subprocess.run(cmd, cwd=str(REPO_ROOT), check=True)
    ext = ".exe" if distdir.name == "win" else ""
    out = distdir / f"{name}{ext}"
    if not out.exists():
        raise SystemExit(f"PyInstaller finished but expected output is missing: {out}")
    if ext == "":
        os.chmod(out, 0o755)
    size_mb = out.stat().st_size / (1024 * 1024)
    print(f"Built {out} ({size_mb:.1f} MiB)")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Build standalone pehredar-core binaries with PyInstaller.")
    parser.add_argument("--platform", choices=["win", "linux", "auto"], default="auto")
    parser.add_argument("--out", default=str(GUI_BIN_ROOT), help="Bin root (default: gui/resources/bin)")
    args = parser.parse_args()

    platform_dir = detect_platform_dir() if args.platform == "auto" else args.platform
    check_pyinstaller()
    if not DB_SRC.exists():
        raise SystemExit(f"Indicator DB not found: {DB_SRC}")

    distdir = Path(args.out) / platform_dir
    distdir.mkdir(parents=True, exist_ok=True)
    gen_dir = REPO_ROOT / "build" / "pyinstaller" / "entries"

    sep = ";" if platform_dir == "win" else ":"
    add_data = f"{DB_SRC}{sep}pehredar/checks"

    outputs = []
    for package, func, name in ENTRIES:
        entry = write_entry_module(gen_dir, package, func, name)
        outputs.append(build_one(entry, name, distdir, REPO_ROOT / "build" / "pyinstaller", add_data))

    print("\nDone. Bundled binaries:")
    for out in outputs:
        print(f"  {out}")


if __name__ == "__main__":
    main()
